; Small C HuC6280 (v0.2, 08/Nov/97)
;
; Taken to HuC (22/Feb/00)
;
;
; This file generated by HuC (v3.21, 2005/04/09, Denki release)
; on Sun Apr 12 12:28:19 2015
;

HUC	= 1

	.include "startup.asm"
	.data
	.bank DATA_BANK

	.code

	.proc _spr_make
	__pushw
	__ldw_s	14
	  call	_spr_set
	__ldw_s	12
	  call	_spr_x
	__ldw_s	10
	  call	_spr_y
	__ldw_s	8
	  call	_spr_pattern
	__ldw_s	6
	  stx	_al
	__ldw_s	4
	  call	_spr_ctrl.2
	__ldw_s	2
	  call	_spr_pal
	__ldw_s	0
	  call	_spr_pri
LL1:

	__addmi	16,__stack
	  rts
	.endp

	.proc _spr_put
	__pushw
	__ldw_s	6
	  call	_spr_set
	__ldw_s	4
	  call	_spr_x
	__ldw_s	2
	  call	_spr_y
	__ldw_s	0
	__stw	<__temp
	__ldwi	2
	  jsr	eqzp
	__lbeq	LL3
	__ldwi	8
	  stx	_al
	__ldwi	8
	  call	_spr_ctrl.2
	__lbra	LL4
LL3:

	__ldwi	8
	  stx	_al
	__ldwi	0
	  call	_spr_ctrl.2
LL4:

LL2:

	__addmi	8,__stack
	  rts
	.endp

	.data
	.dw $0
_knight:
	.incspr "knight4.pcx",0,0,2,12
	.code
	.data
	.dw $0
_knightpal:
	.incpal "knight4.pcx"
	.code
	.data
	.dw $0
_ennemy:
	.incspr "ennemy.pcx",0,0,1,3
	.code
	.data
	.dw $0
_ennemypal:
	.incpal "ennemy.pcx"
	.code
	.data
	.dw $0
_levelmap:
	.incbin "timeline.FMP"

	.code
	.data
	.dw $1000
_leveltiles__data__:
	.inctile "tile.pcx",0,0,6,7
	.code
	.data
	.dw $0
_levelpal0:
	.incpal "tile.pcx"
	.code
	.proc _main
	__addmi	-2,__stack
	__farptr	_levelmap,_bl,_si
	__ldwi	48
	__stw	_ax
	__ldwi	14
	  call	_set_map_data.3
	__ldwi	_leveltiles
	__stw	_di
	  call	_set_tile_data.1
	__ldwi	4096
	  call	_load_tile
	__ldwi	0
	  stx	_al
	__ldwi	0
	  stx	_ah
	__ldwi	0
	__phw	4,4
	__ldwi	0
	__phw	2
	__ldwi	32
	  stx	_dl
	__ldwi	14
	  stx	_dh
	  call	_load_map.6
	__ldwi	0
	  stx	_al
	__farptr	_levelpal0,_bl,_si
	__ldwi	1
	  stx	_cl
	  call	_load_palette.3
	__ldwi	20480
	__stw	_ram_knight_addr
	__ldwi	20736
	__stw	_ram_knight_addr2
	__ldwi	0
	__pushw
	__ldwi	112
	__pushw
	__ldwi	96
	__pushw
	__ldw	_ram_knight_addr
	__pushw
	__ldwi	185
	__pushw
	__ldwi	17
	__pushw
	__ldwi	0
	__pushw
	__ldwi	1
	  call	_spr_make
	_set_sprpal	#0,_knightpal,#1
	__ldw	_ram_knight_addr
	__stw	_di
	__farptr	_knight,_bl,_si
	__ldwi	1536
	__stw	_cx
	  call	_load_vram.3
	_set_sprpal	#1,_ennemypal,#1
	__ldwi	24576
	__stw	_di
	__farptr	_ennemy,_bl,_si
	__ldwi	512
	__stw	_cx
	  call	_load_vram.3
	__ldwi	0
	__stw	_state_knight
	__ldwi	0
	__stw	_tics_knight
	__ldwi	0
	__stw	_walk_knight
	__ldwi	0
	__stw	_frame_knight
	__ldwi	112
	__stw	_knight_x
	__ldwi	96
	__stw	_knight_y
	__ldwi	0
	__stw	_ennemy_x
	__ldwi	0
	__stw	_ennemy_y
	__ldwi	0
	__stw	_nb_ennemy
	__ldwi	0
	__stw	_nb_ennemy_2
	__ldwi	0
	__stw	_nb_ennemy_3
	__ldwi	0
	__stw	_time_move
	__ldwi	1
	__stw	_univers_time
	__ldwi	0
	__stw	_counter
	__stwi_s	0,0
LL6:

	__ldw_s	0
	__stw	<__temp
	__ldwi	16
	  jsr	ltzp
	__lbne	LL8
	__lbra	LL9
LL7:

	__ldw_s	0
	__incw_s	0
	__lbra	LL6
LL8:

	__ldw_s	0
	__aslw
	__addwi	_table_z
	__pushw
	__ldwi	1
	__stwps
	__ldw_s	0
	__aslw
	__addwi	_table_z_2
	__pushw
	__ldwi	1
	__stwps
	__ldw_s	0
	__aslw
	__addwi	_table_z_3
	__pushw
	__ldwi	1
	__stwps
	__lbra	LL7
LL9:

	__ldwi	1
	  stx	_al
	__ldwi	0
	  call	_set_font_color.2
	  call	_load_default_font
LL10:

LL11:

LL12:

	  ldy	#0
	  call	_vsync
	__ldwi	0
	  call	_joy
	__stw	_j1
	__ldw	_counter
	incw	_counter
	  call	_player_machine
	  call	_ennemy_machine
	  call	_physique
	__ldw	_univers_time
	__phw	4,4
	__ldwi	5
	__phb	2
	__ldwi	5
	__phb	1
	__ldwi	0
	  call	_put_number.4
	__ldw	_state_knight
	__phw	4,4
	__ldwi	5
	__phb	2
	__ldwi	5
	__phb	1
	__ldwi	1
	  call	_put_number.4
	  ldy	#0
	  call	_satb_update
	__lbra	LL12
LL13:

LL5:

	__addmi	2,__stack
	  rts
	.endp

	.proc _player_machine
	__ldwi	0
	  call	_spr_set
	__ldwi	LL15
	__pushw
	__ldw	_univers_time
	  jmp	___case
LL17:

	__ldwi	20480
	__stw	_ram_knight_addr
	__ldwi	20736
	__stw	_ram_knight_addr2
	__lbra	LL16
LL18:

	__ldwi	20992
	__stw	_ram_knight_addr
	__ldwi	21248
	__stw	_ram_knight_addr2
	__lbra	LL16
LL19:

	__ldwi	21504
	__stw	_ram_knight_addr
	__ldwi	21760
	__stw	_ram_knight_addr2
	__lbra	LL16
LL20:

	__ldwi	20480
	__stw	_ram_knight_addr
	__ldwi	20736
	__stw	_ram_knight_addr2
	__lbra	LL16
	__lbra	LL16
LL15:

	.dw	1,LL17,2,LL18,3,LL19
	.dw	LL20,0
LL16:

	__ldw	_state_knight
	__stw	<__temp
	__ldwi	0
	  jsr	eqzp
	__lbeq	LL21
	  call	_player_knight_0
LL21:

	__ldw	_state_knight
	__stw	<__temp
	__ldwi	1
	  jsr	eqzp
	__lbeq	LL22
	  call	_player_knight_1
LL22:

	__ldw	_state_knight
	__stw	<__temp
	__ldwi	2
	  jsr	eqzp
	__lbeq	LL23
	  call	_player_knight_2
LL23:

	__ldw	_state_knight
	__stw	<__temp
	__ldwi	3
	  jsr	eqzp
	__lbeq	LL24
	  call	_player_knight_3
LL24:

	__ldw	_state_knight
	__stw	<__temp
	__ldwi	4
	  jsr	eqzp
	__lbeq	LL25
	  call	_player_knight_4
LL25:

LL14:

	  rts
	.endp

	.proc _player_knight_0
	__ldw	_tics_knight
	incw	_tics_knight
	__ldw	_tics_knight
	__stw	<__temp
	__ldwi	6
	  jsr	gtzp
	__lbeq	LL27
	__ldwi	0
	__stw	_tics_knight
	__ldw	_frame_knight
	incw	_frame_knight
	__ldw	_frame_knight
	__stw	<__temp
	__ldwi	1
	  jsr	gtzp
	__lbeq	LL28
	__ldwi	0
	__stw	_frame_knight
LL28:

	__ldw	_frame_knight
	__stw	<__temp
	__ldwi	0
	  jsr	eqzp
	__lbeq	LL29
	__ldw	_ram_knight_addr
	  call	_spr_pattern
LL29:

	__ldw	_frame_knight
	__stw	<__temp
	__ldwi	1
	  jsr	eqzp
	__lbeq	LL30
	__ldw	_ram_knight_addr2
	  call	_spr_pattern
LL30:

LL27:

	__ldw	_j1
	__andwi	128
	__tstw
	__lbeq	LL31
	__ldwi	0
	__stw	_tics_knight
	__ldwi	0
	__stw	_frame_knight
	__ldwi	1
	__stw	_state_knight
	__ldw	_ram_knight_addr
	  call	_spr_pattern
	__ldwi	1
	__stw	_dir_knight
LL31:

	__ldw	_j1
	__andwi	32
	__tstw
	__lbeq	LL32
	__ldwi	0
	__stw	_tics_knight
	__ldwi	0
	__stw	_frame_knight
	__ldwi	1
	__stw	_state_knight
	__ldw	_ram_knight_addr
	  call	_spr_pattern
	__ldwi	2
	__stw	_dir_knight
LL32:

	__ldw	_j1
	__andwi	16
	__tstw
	__lbeq	LL33
	__ldwi	0
	__stw	_tics_knight
	__ldwi	0
	__stw	_frame_knight
	__ldwi	1
	__stw	_state_knight
	__ldw	_ram_knight_addr
	  call	_spr_pattern
	__ldwi	3
	__stw	_dir_knight
LL33:

	__ldw	_j1
	__andwi	64
	__tstw
	__lbeq	LL34
	__ldwi	0
	__stw	_tics_knight
	__ldwi	0
	__stw	_frame_knight
	__ldwi	1
	__stw	_state_knight
	__ldw	_ram_knight_addr
	  call	_spr_pattern
	__ldwi	4
	__stw	_dir_knight
LL34:

	__ldw	_j1
	__andwi	128
	__tstw
	__lbeq	LL36
	__ldw	_j1
	__andwi	16
LL36:

	__boolw
	__tstw
	__lbeq	LL35
	__ldwi	0
	__stw	_tics_knight
	__ldwi	0
	__stw	_frame_knight
	__ldwi	1
	__stw	_state_knight
	__ldw	_ram_knight_addr
	  call	_spr_pattern
	__ldwi	5
	__stw	_dir_knight
LL35:

	__ldw	_j1
	__andwi	32
	__tstw
	__lbeq	LL38
	__ldw	_j1
	__andwi	16
LL38:

	__boolw
	__tstw
	__lbeq	LL37
	__ldwi	0
	__stw	_tics_knight
	__ldwi	0
	__stw	_frame_knight
	__ldwi	1
	__stw	_state_knight
	__ldw	_ram_knight_addr
	  call	_spr_pattern
	__ldwi	6
	__stw	_dir_knight
LL37:

	__ldw	_j1
	__andwi	128
	__tstw
	__lbeq	LL40
	__ldw	_j1
	__andwi	64
LL40:

	__boolw
	__tstw
	__lbeq	LL39
	__ldwi	0
	__stw	_tics_knight
	__ldwi	0
	__stw	_frame_knight
	__ldwi	1
	__stw	_state_knight
	__ldw	_ram_knight_addr
	  call	_spr_pattern
	__ldwi	7
	__stw	_dir_knight
LL39:

	__ldw	_j1
	__andwi	32
	__tstw
	__lbeq	LL42
	__ldw	_j1
	__andwi	64
LL42:

	__boolw
	__tstw
	__lbeq	LL41
	__ldwi	0
	__stw	_tics_knight
	__ldwi	0
	__stw	_frame_knight
	__ldwi	1
	__stw	_state_knight
	__ldw	_ram_knight_addr
	  call	_spr_pattern
	__ldwi	8
	__stw	_dir_knight
LL41:

	__ldw	_j1
	__andwi	1
	__tstw
	__lbeq	LL43
	__ldwi	0
	__stw	_tics_knight
	__ldwi	0
	__stw	_frame_knight
	__ldwi	2
	__stw	_state_knight
	__ldw	_ram_knight_addr
	  call	_spr_pattern
LL43:

	__ldw	_j1
	__andwi	2
	__tstw
	__lbeq	LL45
	__ldw	_j1
	__andwi	128
LL45:

	__boolw
	__tstw
	__lbeq	LL44
	__ldwi	1
	__stw	_time_move
	__ldwi	0
	__stw	_tics_knight
	__ldwi	0
	__stw	_frame_knight
	__ldwi	4
	__stw	_state_knight
	__ldw	_ram_knight_addr
	  call	_spr_pattern
LL44:

	__ldw	_j1
	__andwi	2
	__tstw
	__lbeq	LL47
	__ldw	_j1
	__andwi	32
LL47:

	__boolw
	__tstw
	__lbeq	LL46
	__ldwi	2
	__stw	_time_move
	__ldwi	0
	__stw	_tics_knight
	__ldwi	0
	__stw	_frame_knight
	__ldwi	4
	__stw	_state_knight
	__ldw	_ram_knight_addr
	  call	_spr_pattern
LL46:

LL26:

	  rts
	.endp

	.proc _player_knight_1
	__ldwi	0
	__stw	_walk_knight
	__ldw	_tics_knight
	incw	_tics_knight
	__ldw	_tics_knight
	__stw	<__temp
	__ldwi	6
	  jsr	gtzp
	__lbeq	LL49
	__ldwi	0
	__stw	_tics_knight
	__ldw	_frame_knight
	incw	_frame_knight
	__ldw	_frame_knight
	__stw	<__temp
	__ldwi	3
	  jsr	gtzp
	__lbeq	LL50
	__ldwi	0
	__stw	_frame_knight
LL50:

	__ldw	_frame_knight
	__stw	<__temp
	__ldwi	0
	  jsr	eqzp
	__lbeq	LL51
	__ldw	_ram_knight_addr
	  call	_spr_pattern
LL51:

	__ldw	_frame_knight
	__stw	<__temp
	__ldwi	1
	  jsr	eqzp
	__lbeq	LL52
	__ldw	_ram_knight_addr
	  call	_spr_pattern
LL52:

	__ldw	_frame_knight
	__stw	<__temp
	__ldwi	2
	  jsr	eqzp
	__lbeq	LL53
	__ldw	_ram_knight_addr
	  call	_spr_pattern
LL53:

	__ldw	_frame_knight
	__stw	<__temp
	__ldwi	3
	  jsr	eqzp
	__lbeq	LL54
	__ldw	_ram_knight_addr
	  call	_spr_pattern
LL54:

LL49:

	__ldw	_j1
	__andwi	128
	__tstw
	__lbeq	LL55
	__ldwi	1
	__stw	_dir_knight
	__ldwi	1
	__stw	_walk_knight
LL55:

	__ldw	_j1
	__andwi	32
	__tstw
	__lbeq	LL56
	__ldwi	2
	__stw	_dir_knight
	__ldwi	1
	__stw	_walk_knight
LL56:

	__ldw	_j1
	__andwi	16
	__tstw
	__lbeq	LL57
	__ldwi	3
	__stw	_dir_knight
	__ldwi	1
	__stw	_walk_knight
LL57:

	__ldw	_j1
	__andwi	64
	__tstw
	__lbeq	LL58
	__ldwi	4
	__stw	_dir_knight
	__ldwi	1
	__stw	_walk_knight
LL58:

	__ldw	_j1
	__andwi	128
	__tstw
	__lbeq	LL60
	__ldw	_j1
	__andwi	16
LL60:

	__boolw
	__tstw
	__lbeq	LL59
	__ldwi	5
	__stw	_dir_knight
	__ldwi	1
	__stw	_walk_knight
LL59:

	__ldw	_j1
	__andwi	32
	__tstw
	__lbeq	LL62
	__ldw	_j1
	__andwi	16
LL62:

	__boolw
	__tstw
	__lbeq	LL61
	__ldwi	6
	__stw	_dir_knight
	__ldwi	1
	__stw	_walk_knight
LL61:

	__ldw	_j1
	__andwi	128
	__tstw
	__lbeq	LL64
	__ldw	_j1
	__andwi	64
LL64:

	__boolw
	__tstw
	__lbeq	LL63
	__ldwi	7
	__stw	_dir_knight
	__ldwi	1
	__stw	_walk_knight
LL63:

	__ldw	_j1
	__andwi	32
	__tstw
	__lbeq	LL66
	__ldw	_j1
	__andwi	64
LL66:

	__boolw
	__tstw
	__lbeq	LL65
	__ldwi	8
	__stw	_dir_knight
	__ldwi	1
	__stw	_walk_knight
LL65:

	__ldw	_j1
	__andwi	1
	__tstw
	__lbeq	LL67
	__ldwi	0
	__stw	_tics_knight
	__ldwi	0
	__stw	_frame_knight
	__ldwi	2
	__stw	_state_knight
	__ldw	_ram_knight_addr
	  call	_spr_pattern
LL67:

	__ldw	_walk_knight
	__stw	<__temp
	__ldwi	0
	  jsr	eqzp
	__lbeq	LL68
	__ldwi	0
	__stw	_tics_knight
	__ldwi	0
	__stw	_frame_knight
	__ldwi	0
	__stw	_state_knight
	__lbra	LL69
LL68:

	__ldw	_dir_knight
	__stw	<__temp
	__ldwi	1
	  jsr	eqzp
	__lbeq	LL70
	__ldw	_knight_x
	__subwi	2
	__stw	_knight_x
LL70:

	__ldw	_dir_knight
	__stw	<__temp
	__ldwi	2
	  jsr	eqzp
	__lbeq	LL71
	__ldw	_knight_x
	__addwi	2
	__stw	_knight_x
LL71:

	__ldw	_dir_knight
	__stw	<__temp
	__ldwi	3
	  jsr	eqzp
	__lbeq	LL72
	__ldw	_knight_y
	__subwi	2
	__stw	_knight_y
LL72:

	__ldw	_dir_knight
	__stw	<__temp
	__ldwi	4
	  jsr	eqzp
	__lbeq	LL73
	__ldw	_knight_y
	__addwi	2
	__stw	_knight_y
LL73:

	__ldw	_dir_knight
	__stw	<__temp
	__ldwi	5
	  jsr	eqzp
	__lbeq	LL74
	__ldw	_knight_x
	__subwi	2
	__stw	_knight_x
	__ldw	_knight_y
	__subwi	2
	__stw	_knight_y
LL74:

	__ldw	_dir_knight
	__stw	<__temp
	__ldwi	6
	  jsr	eqzp
	__lbeq	LL75
	__ldw	_knight_x
	__addwi	2
	__stw	_knight_x
	__ldw	_knight_y
	__subwi	2
	__stw	_knight_y
LL75:

	__ldw	_dir_knight
	__stw	<__temp
	__ldwi	7
	  jsr	eqzp
	__lbeq	LL76
	__ldw	_knight_x
	__subwi	2
	__stw	_knight_x
	__ldw	_knight_y
	__addwi	2
	__stw	_knight_y
LL76:

	__ldw	_dir_knight
	__stw	<__temp
	__ldwi	8
	  jsr	eqzp
	__lbeq	LL77
	__ldw	_knight_x
	__addwi	2
	__stw	_knight_x
	__ldw	_knight_y
	__addwi	2
	__stw	_knight_y
LL77:

LL69:

LL48:

	  rts
	.endp

	.proc _player_knight_2
	__addmi	-10,__stack
	__ldwi	LL79
	__pushw
	__ldw	_univers_time
	  jmp	___case
LL81:

	__ldwi	_table_x
	__stw	__ptr
	__ldwp	__ptr
	__stw_s	8
	__ldwi	_table_y
	__stw	__ptr
	__ldwp	__ptr
	__stw_s	6
	__lbra	LL80
LL82:

	__ldwi	_table_x_2
	__stw	__ptr
	__ldwp	__ptr
	__stw_s	8
	__ldwi	_table_y_2
	__stw	__ptr
	__ldwp	__ptr
	__stw_s	6
	__lbra	LL80
LL83:

	__ldwi	_table_x_3
	__stw	__ptr
	__ldwp	__ptr
	__stw_s	8
	__ldwi	_table_y_3
	__stw	__ptr
	__ldwp	__ptr
	__stw_s	6
	__lbra	LL80
	__lbra	LL80
LL79:

	.dw	1,LL81,2,LL82,3,LL83
	.dw	LL80,0
LL80:

	__stwi_s	0,4
LL84:

	__ldw_s	4
	__stw	<__temp
	__ldw	_nb_ennemy
	  jsr	ltzp
	__lbne	LL86
	__lbra	LL87
LL85:

	__ldw_s	4
	__incw_s	4
	__lbra	LL84
LL86:

	__ldwi	LL88
	__pushw
	__ldw	_univers_time
	  jmp	___case
LL90:

	__ldw_s	4
	__aslw
	__addwi	_table_x
	__stw	__ptr
	__ldwp	__ptr
	__subw	_knight_x
	__stw_s	2
	__ldw_s	4
	__aslw
	__addwi	_table_y
	__stw	__ptr
	__ldwp	__ptr
	__subw	_knight_y
	__stw_s	0
	__lbra	LL89
LL91:

	__ldw_s	4
	__aslw
	__addwi	_table_x_2
	__stw	__ptr
	__ldwp	__ptr
	__subw	_knight_x
	__stw_s	2
	__ldw_s	4
	__aslw
	__addwi	_table_y_2
	__stw	__ptr
	__ldwp	__ptr
	__subw	_knight_y
	__stw_s	0
	__lbra	LL89
LL92:

	__ldw_s	4
	__aslw
	__addwi	_table_x_3
	__stw	__ptr
	__ldwp	__ptr
	__subw	_knight_x
	__stw_s	2
	__ldw_s	4
	__aslw
	__addwi	_table_y_3
	__stw	__ptr
	__ldwp	__ptr
	__subw	_knight_y
	__stw_s	0
	__lbra	LL89
	__lbra	LL89
LL88:

	.dw	1,LL90,2,LL91,3,LL92
	.dw	LL89,0
LL89:

	__ldw_s	2
	__pushw
	__ldwi	16
	__negw
	  jsr	gt
	__lbeq	LL94
	__ldw_s	2
	__stw	<__temp
	__ldwi	32
	  jsr	ltzp
LL94:

	__boolw
	__tstw
	__lbeq	LL95
	__ldw_s	0
	__pushw
	__ldwi	16
	__negw
	  jsr	gt
LL95:

	__boolw
	__tstw
	__lbeq	LL96
	__ldw_s	0
	__stw	<__temp
	__ldwi	32
	  jsr	ltzp
LL96:

	__boolw
	__tstw
	__lbeq	LL93
	__ldwi	LL97
	__pushw
	__ldw	_univers_time
	  jmp	___case
LL99:

	__ldw_s	4
	__aslw
	__addwi	_table_z
	__pushw
	__ldwi	0
	__stwps
	__lbra	LL98
LL100:

	__ldw_s	4
	__aslw
	__addwi	_table_z_2
	__pushw
	__ldwi	0
	__stwps
	__lbra	LL98
LL101:

	__ldw_s	4
	__aslw
	__addwi	_table_z_3
	__pushw
	__ldwi	0
	__stwps
	__lbra	LL98
	__lbra	LL98
LL97:

	.dw	1,LL99,2,LL100,3,LL101
	.dw	LL98,0
LL98:

LL93:

	__lbra	LL85
LL87:

	__ldwi	0
	__stw	_state_knight
LL78:

	__addmi	10,__stack
	  rts
	.endp

	.proc _player_knight_3
	__ldwi	0
	__stw	_state_knight
LL102:

	  rts
	.endp

	.proc _player_knight_4
	__addmi	-4,__stack
	__ldw	_univers_time
	__stw	<__temp
	__ldwi	1
	  jsr	eqzp
	__lbeq	LL105
	__ldw	_time_move
	__stw	<__temp
	__ldwi	2
	  jsr	eqzp
LL105:

	__boolw
	__tstw
	__lbeq	LL104
	__stwi_s	0,0
	__stwi_s	0,2
LL106:

	__ldw_s	2
	__stw	<__temp
	__ldwi	256
	  jsr	ltzp
	__lbne	LL108
	__lbra	LL109
LL107:

	__ldw_s	2
	__incw_s	2
	__lbra	LL106
LL108:

	__ldw_s	0
	__incw_s	0
	__ldwi	0
	__pushw
	__ldw_s	2
	__pushw
	__ldwi	0
	__pushw
	__ldwi	0
	__pushw
	__ldwi	253
	__pushw
	__ldwi	192
	  call	_scroll
	__ldw_s	2
	__pushw
	__ldwi	5
	  jsr	smod
	__stw	<__temp
	__ldwi	0
	  jsr	eqzp
	__lbeq	LL110
	  ldy	#0
	  call	_vsync
LL110:

	__lbra	LL107
LL109:

LL104:

	__ldw	_univers_time
	__stw	<__temp
	__ldwi	2
	  jsr	eqzp
	__lbeq	LL112
	__ldw	_time_move
	__stw	<__temp
	__ldwi	2
	  jsr	eqzp
LL112:

	__boolw
	__tstw
	__lbeq	LL111
	__ldwi	0
	  stx	_al
	__ldwi	0
	  stx	_ah
	__ldwi	16
	__phw	4,4
	__ldwi	0
	__phw	2
	__ldwi	32
	  stx	_dl
	__ldwi	14
	  stx	_dh
	  call	_load_map.6
	__stwi_s	0,0
	__stwi_s	0,2
LL113:

	__ldw_s	2
	__stw	<__temp
	__ldwi	256
	  jsr	ltzp
	__lbne	LL115
	__lbra	LL116
LL114:

	__ldw_s	2
	__incw_s	2
	__lbra	LL113
LL115:

	__ldw_s	0
	__incw_s	0
	__ldwi	0
	__pushw
	__ldw_s	2
	__pushw
	__ldwi	0
	__pushw
	__ldwi	0
	__pushw
	__ldwi	253
	__pushw
	__ldwi	192
	  call	_scroll
	__ldw_s	2
	__pushw
	__ldwi	5
	  jsr	smod
	__stw	<__temp
	__ldwi	0
	  jsr	eqzp
	__lbeq	LL117
	  ldy	#0
	  call	_vsync
LL117:

	__lbra	LL114
LL116:

LL111:

	__ldw	_univers_time
	__stw	<__temp
	__ldwi	2
	  jsr	eqzp
	__lbeq	LL119
	__ldw	_time_move
	__stw	<__temp
	__ldwi	1
	  jsr	eqzp
LL119:

	__boolw
	__tstw
	__lbeq	LL118
	__ldwi	0
	  stx	_al
	__ldwi	0
	  stx	_ah
	__ldwi	0
	__phw	4,4
	__ldwi	0
	__phw	2
	__ldwi	32
	  stx	_dl
	__ldwi	14
	  stx	_dh
	  call	_load_map.6
	__stwi_s	256,0
	__stwi_s	0,2
LL120:

	__ldw_s	2
	__stw	<__temp
	__ldwi	256
	  jsr	ltzp
	__lbne	LL122
	__lbra	LL123
LL121:

	__ldw_s	2
	__incw_s	2
	__lbra	LL120
LL122:

	__ldw_s	0
	__subwi	1
	__stw_s	0
	__addwi	1
	__ldwi	0
	__pushw
	__ldw_s	2
	__pushw
	__ldwi	0
	__pushw
	__ldwi	0
	__pushw
	__ldwi	253
	__pushw
	__ldwi	192
	  call	_scroll
	__ldw_s	2
	__pushw
	__ldwi	5
	  jsr	smod
	__stw	<__temp
	__ldwi	0
	  jsr	eqzp
	__lbeq	LL124
	  ldy	#0
	  call	_vsync
LL124:

	__lbra	LL121
LL123:

LL118:

	__ldw	_univers_time
	__stw	<__temp
	__ldwi	3
	  jsr	eqzp
	__lbeq	LL126
	__ldw	_time_move
	__stw	<__temp
	__ldwi	1
	  jsr	eqzp
LL126:

	__boolw
	__tstw
	__lbeq	LL125
	__stwi_s	256,0
	__stwi_s	0,2
LL127:

	__ldw_s	2
	__stw	<__temp
	__ldwi	256
	  jsr	ltzp
	__lbne	LL129
	__lbra	LL130
LL128:

	__ldw_s	2
	__incw_s	2
	__lbra	LL127
LL129:

	__ldw_s	0
	__subwi	1
	__stw_s	0
	__addwi	1
	__ldwi	0
	__pushw
	__ldw_s	2
	__pushw
	__ldwi	0
	__pushw
	__ldwi	0
	__pushw
	__ldwi	253
	__pushw
	__ldwi	192
	  call	_scroll
	__ldw_s	2
	__pushw
	__ldwi	5
	  jsr	smod
	__stw	<__temp
	__ldwi	0
	  jsr	eqzp
	__lbeq	LL131
	  ldy	#0
	  call	_vsync
LL131:

	__lbra	LL128
LL130:

LL125:

	__ldw	_time_move
	__stw	<__temp
	__ldwi	1
	  jsr	eqzp
	__lbeq	LL132
	__ldw	_univers_time
	__stw	<__temp
	__ldwi	1
	  jsr	gtzp
	__lbeq	LL133
	__ldw	_univers_time
	__subwi	1
	__stw	_univers_time
	__addwi	1
LL133:

LL132:

	__ldw	_time_move
	__stw	<__temp
	__ldwi	2
	  jsr	eqzp
	__lbeq	LL134
	__ldw	_univers_time
	__stw	<__temp
	__ldwi	3
	  jsr	ltzp
	__lbeq	LL135
	__ldw	_univers_time
	incw	_univers_time
LL135:

LL134:

	__ldwi	0
	__stw	_state_knight
LL103:

	__addmi	4,__stack
	  rts
	.endp

	.proc _physique
	__ldwi	0
	__pushw
	__ldw	_knight_x
	__pushw
	__ldw	_knight_y
	__pushw
	__ldw	_dir_knight
	  call	_spr_put
LL136:

	  rts
	.endp

	.proc _ennemy_machine
	__addmi	-2,__stack
	__ldw	_counter
	__pushw
	__ldwi	100
	  jsr	smod
	__stw	<__temp
	__ldwi	0
	  jsr	eqzp
	__lbeq	LL139
	__ldw	_nb_ennemy
	__stw	<__temp
	__ldwi	16
	  jsr	ltzp
LL139:

	__boolw
	__tstw
	__lbeq	LL138
	__ldw	_nb_ennemy
	incw	_nb_ennemy
	  call	_ennemy_cre
LL138:

	__ldw	_counter
	__pushw
	__ldwi	10
	  jsr	smod
	__stw	<__temp
	__ldwi	0
	  jsr	eqzp
	__lbeq	LL140
	__stwi_s	0,0
LL141:

	__ldw_s	0
	__stw	<__temp
	__ldw	_nb_ennemy
	  jsr	ltzp
	__lbne	LL143
	__lbra	LL144
LL142:

	__ldw_s	0
	__incw_s	0
	__lbra	LL141
LL143:

	__ldw_s	0
	__aslw
	__addwi	_table_x
	__stw	__ptr
	__ldwp	__ptr
	__stw	<__temp
	__ldwi	120
	  jsr	ltzp
	__lbeq	LL145
	__ldw_s	0
	__aslw
	__addwi	_table_x
	__pushw
	__stw	__ptr
	__ldwp	__ptr
	__addwi	1
	__stwps
	__subwi	1
LL145:

	__ldw_s	0
	__aslw
	__addwi	_table_x
	__stw	__ptr
	__ldwp	__ptr
	__stw	<__temp
	__ldwi	120
	  jsr	gtzp
	__lbeq	LL146
	__ldw_s	0
	__aslw
	__addwi	_table_x
	__pushw
	__stw	__ptr
	__ldwp	__ptr
	__subwi	1
	__stwps
	__addwi	1
LL146:

	__ldw_s	0
	__aslw
	__addwi	_table_y
	__stw	__ptr
	__ldwp	__ptr
	__stw	<__temp
	__ldwi	104
	  jsr	ltzp
	__lbeq	LL147
	__ldw_s	0
	__aslw
	__addwi	_table_y
	__pushw
	__stw	__ptr
	__ldwp	__ptr
	__addwi	1
	__stwps
	__subwi	1
LL147:

	__ldw_s	0
	__aslw
	__addwi	_table_y
	__stw	__ptr
	__ldwp	__ptr
	__stw	<__temp
	__ldwi	104
	  jsr	gtzp
	__lbeq	LL148
	__ldw_s	0
	__aslw
	__addwi	_table_y
	__pushw
	__stw	__ptr
	__ldwp	__ptr
	__subwi	1
	__stwps
	__addwi	1
LL148:

	__ldw_s	0
	__aslw
	__addwi	_table_x_2
	__stw	__ptr
	__ldwp	__ptr
	__stw	<__temp
	__ldwi	120
	  jsr	ltzp
	__lbeq	LL149
	__ldw_s	0
	__aslw
	__addwi	_table_x_2
	__pushw
	__stw	__ptr
	__ldwp	__ptr
	__addwi	1
	__stwps
	__subwi	1
LL149:

	__ldw_s	0
	__aslw
	__addwi	_table_x_2
	__stw	__ptr
	__ldwp	__ptr
	__stw	<__temp
	__ldwi	120
	  jsr	gtzp
	__lbeq	LL150
	__ldw_s	0
	__aslw
	__addwi	_table_x_2
	__pushw
	__stw	__ptr
	__ldwp	__ptr
	__subwi	1
	__stwps
	__addwi	1
LL150:

	__ldw_s	0
	__aslw
	__addwi	_table_y_2
	__stw	__ptr
	__ldwp	__ptr
	__stw	<__temp
	__ldwi	104
	  jsr	ltzp
	__lbeq	LL151
	__ldw_s	0
	__aslw
	__addwi	_table_y_2
	__pushw
	__stw	__ptr
	__ldwp	__ptr
	__addwi	1
	__stwps
	__subwi	1
LL151:

	__ldw_s	0
	__aslw
	__addwi	_table_y_2
	__stw	__ptr
	__ldwp	__ptr
	__stw	<__temp
	__ldwi	104
	  jsr	gtzp
	__lbeq	LL152
	__ldw_s	0
	__aslw
	__addwi	_table_y_2
	__pushw
	__stw	__ptr
	__ldwp	__ptr
	__subwi	1
	__stwps
	__addwi	1
LL152:

	__ldw_s	0
	__aslw
	__addwi	_table_x_3
	__stw	__ptr
	__ldwp	__ptr
	__stw	<__temp
	__ldwi	120
	  jsr	ltzp
	__lbeq	LL153
	__ldw_s	0
	__aslw
	__addwi	_table_x_3
	__pushw
	__stw	__ptr
	__ldwp	__ptr
	__addwi	1
	__stwps
	__subwi	1
LL153:

	__ldw_s	0
	__aslw
	__addwi	_table_x_3
	__stw	__ptr
	__ldwp	__ptr
	__stw	<__temp
	__ldwi	120
	  jsr	gtzp
	__lbeq	LL154
	__ldw_s	0
	__aslw
	__addwi	_table_x_3
	__pushw
	__stw	__ptr
	__ldwp	__ptr
	__subwi	1
	__stwps
	__addwi	1
LL154:

	__ldw_s	0
	__aslw
	__addwi	_table_y_3
	__stw	__ptr
	__ldwp	__ptr
	__stw	<__temp
	__ldwi	104
	  jsr	ltzp
	__lbeq	LL155
	__ldw_s	0
	__aslw
	__addwi	_table_y_3
	__pushw
	__stw	__ptr
	__ldwp	__ptr
	__addwi	1
	__stwps
	__subwi	1
LL155:

	__ldw_s	0
	__aslw
	__addwi	_table_y_3
	__stw	__ptr
	__ldwp	__ptr
	__stw	<__temp
	__ldwi	104
	  jsr	gtzp
	__lbeq	LL156
	__ldw_s	0
	__aslw
	__addwi	_table_y_3
	__pushw
	__stw	__ptr
	__ldwp	__ptr
	__subwi	1
	__stwps
	__addwi	1
LL156:

	__ldwi	LL157
	__pushw
	__ldw	_univers_time
	  jmp	___case
LL159:

	__ldw_s	0
	__aslw
	__addwi	_table_z
	__stw	__ptr
	__ldwp	__ptr
	__stw	<__temp
	__ldwi	1
	  jsr	eqzp
	__lbeq	LL160
	__ldw_s	0
	__addwi	1
	  ldy	#1
	  call	_spr_show
	__ldw_s	0
	__addwi	1
	__pushw
	__ldw_s	2
	__aslw
	__addwi	_table_x
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldw_s	4
	__aslw
	__addwi	_table_y
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldwi	1
	  call	_spr_put
	__ldwi	24576
	  call	_spr_pattern
	__lbra	LL161
LL160:

	__ldw_s	0
	__addwi	1
	  ldy	#1
	  call	_spr_hide
LL161:

	__lbra	LL158
LL162:

	__ldw_s	0
	__aslw
	__addwi	_table_z_2
	__stw	__ptr
	__ldwp	__ptr
	__stw	<__temp
	__ldwi	1
	  jsr	eqzp
	__lbeq	LL163
	__ldw_s	0
	__addwi	1
	  ldy	#1
	  call	_spr_show
	__ldw_s	0
	__addwi	1
	__pushw
	__ldw_s	2
	__aslw
	__addwi	_table_x_2
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldw_s	4
	__aslw
	__addwi	_table_y_2
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldwi	1
	  call	_spr_put
	__ldwi	24640
	  call	_spr_pattern
	__lbra	LL164
LL163:

	__ldw_s	0
	__addwi	1
	  ldy	#1
	  call	_spr_hide
LL164:

	__lbra	LL158
LL165:

	__ldw_s	0
	__aslw
	__addwi	_table_z_3
	__stw	__ptr
	__ldwp	__ptr
	__stw	<__temp
	__ldwi	1
	  jsr	eqzp
	__lbeq	LL166
	__ldw_s	0
	__addwi	1
	  ldy	#1
	  call	_spr_show
	__ldw_s	0
	__addwi	1
	__pushw
	__ldw_s	2
	__aslw
	__addwi	_table_x_3
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldw_s	4
	__aslw
	__addwi	_table_y_3
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldwi	1
	  call	_spr_put
	__ldwi	24704
	  call	_spr_pattern
	__lbra	LL167
LL166:

	__ldw_s	0
	__addwi	1
	  ldy	#1
	  call	_spr_hide
LL167:

	__lbra	LL158
	__lbra	LL158
LL157:

	.dw	1,LL159,2,LL162,3,LL165
	.dw	LL158,0
LL158:

	__lbra	LL142
LL144:

LL140:

LL137:

	__addmi	2,__stack
	  rts
	.endp

	.proc _ennemy_cre
	__addmi	-6,__stack
	__ldw	_counter
	__addw	_knight_x
	__addw	_tics_knight
	  call	_srand
	__pea_s	4
	__ldwi	4
	  call	_random
	__stwps
	__pea_s	2
	__ldwi	16
	  call	_random
	__pushw
	__ldwi	16
	  jsr	smul
	__stwps
	__pea_s	0
	__ldwi	14
	  call	_random
	__pushw
	__ldwi	16
	  jsr	smul
	__stwps
	__ldw_s	4
	__phw	4,4
	__ldwi	5
	__phb	2
	__ldwi	5
	__phb	1
	__ldwi	3
	  call	_put_number.4
	__ldw_s	4
	__stw	<__temp
	__ldwi	0
	  jsr	eqzp
	__lbeq	LL169
	__ldw	_nb_ennemy
	__aslw
	__addwi	_table_x
	__pushw
	__ldw_s	4
	__stwps
	__ldw	_nb_ennemy
	__aslw
	__addwi	_table_y
	__pushw
	__ldwi	0
	__stwps
LL169:

	__ldw_s	4
	__stw	<__temp
	__ldwi	1
	  jsr	eqzp
	__lbeq	LL170
	__ldw	_nb_ennemy
	__aslw
	__addwi	_table_x
	__pushw
	__ldw_s	4
	__stwps
	__ldw	_nb_ennemy
	__aslw
	__addwi	_table_y
	__pushw
	__ldwi	224
	__stwps
LL170:

	__ldw_s	4
	__stw	<__temp
	__ldwi	2
	  jsr	eqzp
	__lbeq	LL171
	__ldw	_nb_ennemy
	__aslw
	__addwi	_table_x
	__pushw
	__ldwi	0
	__stwps
	__ldw	_nb_ennemy
	__aslw
	__addwi	_table_y
	__pushw
	__ldw_s	2
	__stwps
LL171:

	__ldw_s	4
	__stw	<__temp
	__ldwi	3
	  jsr	eqzp
	__lbeq	LL172
	__ldw	_nb_ennemy
	__aslw
	__addwi	_table_x
	__pushw
	__ldwi	256
	__stwps
	__ldw	_nb_ennemy
	__aslw
	__addwi	_table_y
	__pushw
	__ldw_s	2
	__stwps
LL172:

	__pea_s	4
	__ldwi	4
	  call	_random
	__stwps
	__pea_s	2
	__ldwi	16
	  call	_random
	__pushw
	__ldwi	16
	  jsr	smul
	__stwps
	__pea_s	0
	__ldwi	14
	  call	_random
	__pushw
	__ldwi	16
	  jsr	smul
	__stwps
	__ldw_s	4
	__phw	4,4
	__ldwi	5
	__phb	2
	__ldwi	5
	__phb	1
	__ldwi	3
	  call	_put_number.4
	__ldw_s	4
	__stw	<__temp
	__ldwi	0
	  jsr	eqzp
	__lbeq	LL173
	__ldw	_nb_ennemy
	__aslw
	__addwi	_table_x_2
	__pushw
	__ldw_s	4
	__stwps
	__ldw	_nb_ennemy
	__aslw
	__addwi	_table_y_2
	__pushw
	__ldwi	0
	__stwps
LL173:

	__ldw_s	4
	__stw	<__temp
	__ldwi	1
	  jsr	eqzp
	__lbeq	LL174
	__ldw	_nb_ennemy
	__aslw
	__addwi	_table_x_2
	__pushw
	__ldw_s	4
	__stwps
	__ldw	_nb_ennemy
	__aslw
	__addwi	_table_y_2
	__pushw
	__ldwi	224
	__stwps
LL174:

	__ldw_s	4
	__stw	<__temp
	__ldwi	2
	  jsr	eqzp
	__lbeq	LL175
	__ldw	_nb_ennemy
	__aslw
	__addwi	_table_x_2
	__pushw
	__ldwi	0
	__stwps
	__ldw	_nb_ennemy
	__aslw
	__addwi	_table_y_2
	__pushw
	__ldw_s	2
	__stwps
LL175:

	__ldw_s	4
	__stw	<__temp
	__ldwi	3
	  jsr	eqzp
	__lbeq	LL176
	__ldw	_nb_ennemy
	__aslw
	__addwi	_table_x_2
	__pushw
	__ldwi	256
	__stwps
	__ldw	_nb_ennemy
	__aslw
	__addwi	_table_y_2
	__pushw
	__ldw_s	2
	__stwps
LL176:

	__pea_s	4
	__ldwi	4
	  call	_random
	__stwps
	__pea_s	2
	__ldwi	16
	  call	_random
	__pushw
	__ldwi	16
	  jsr	smul
	__stwps
	__pea_s	0
	__ldwi	14
	  call	_random
	__pushw
	__ldwi	16
	  jsr	smul
	__stwps
	__ldw_s	4
	__phw	4,4
	__ldwi	5
	__phb	2
	__ldwi	5
	__phb	1
	__ldwi	3
	  call	_put_number.4
	__ldw_s	4
	__stw	<__temp
	__ldwi	0
	  jsr	eqzp
	__lbeq	LL177
	__ldw	_nb_ennemy
	__aslw
	__addwi	_table_x_3
	__pushw
	__ldw_s	4
	__stwps
	__ldw	_nb_ennemy
	__aslw
	__addwi	_table_y_3
	__pushw
	__ldwi	0
	__stwps
LL177:

	__ldw_s	4
	__stw	<__temp
	__ldwi	1
	  jsr	eqzp
	__lbeq	LL178
	__ldw	_nb_ennemy
	__aslw
	__addwi	_table_x_3
	__pushw
	__ldw_s	4
	__stwps
	__ldw	_nb_ennemy
	__aslw
	__addwi	_table_y_3
	__pushw
	__ldwi	224
	__stwps
LL178:

	__ldw_s	4
	__stw	<__temp
	__ldwi	2
	  jsr	eqzp
	__lbeq	LL179
	__ldw	_nb_ennemy
	__aslw
	__addwi	_table_x_3
	__pushw
	__ldwi	0
	__stwps
	__ldw	_nb_ennemy
	__aslw
	__addwi	_table_y_3
	__pushw
	__ldw_s	2
	__stwps
LL179:

	__ldw_s	4
	__stw	<__temp
	__ldwi	3
	  jsr	eqzp
	__lbeq	LL180
	__ldw	_nb_ennemy
	__aslw
	__addwi	_table_x_3
	__pushw
	__ldwi	256
	__stwps
	__ldw	_nb_ennemy
	__aslw
	__addwi	_table_y_3
	__pushw
	__ldw_s	2
	__stwps
LL180:

	__ldwi	LL181
	__pushw
	__ldw	_univers_time
	  jmp	___case
LL183:

	__ldw	_nb_ennemy
	__pushw
	__ldw	_nb_ennemy
	__aslw
	__addwi	_table_x
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldw	_nb_ennemy
	__aslw
	__addwi	_table_y
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldwi	24576
	__pushw
	__ldwi	185
	__pushw
	__ldwi	0
	__pushw
	__ldwi	1
	__pushw
	__ldwi	1
	  call	_spr_make
	__lbra	LL182
LL184:

	__ldw	_nb_ennemy
	__pushw
	__ldw	_nb_ennemy
	__aslw
	__addwi	_table_x_2
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldw	_nb_ennemy
	__aslw
	__addwi	_table_y_2
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldwi	24576
	__pushw
	__ldwi	185
	__pushw
	__ldwi	0
	__pushw
	__ldwi	1
	__pushw
	__ldwi	1
	  call	_spr_make
	__lbra	LL182
LL185:

	__ldw	_nb_ennemy
	__pushw
	__ldw	_nb_ennemy
	__aslw
	__addwi	_table_x_3
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldw	_nb_ennemy
	__aslw
	__addwi	_table_y_3
	__stw	__ptr
	__ldwp	__ptr
	__pushw
	__ldwi	24576
	__pushw
	__ldwi	185
	__pushw
	__ldwi	0
	__pushw
	__ldwi	1
	__pushw
	__ldwi	1
	  call	_spr_make
	__lbra	LL182
	__lbra	LL182
LL181:

	.dw	1,LL183,2,LL184,3,LL185
	.dw	LL182,0
LL182:

LL168:

	__addmi	6,__stack
	  rts
	.endp

	.data
	.bank CONST_BANK
	.org $4000
LL0:
	.db	0,0,0,0,0,0,0,0
	.db	0,0,0,0,0,0,0,0
	.db	0,0,0,0,0,0,0,0
	.db	0,0,0,0,0,0,0,0
	.db	0,0,0,0,0,0,0,0
	.db	0,0
_leveltiles:
	.dw	42
	.dw	16
	.dw	BANK(_leveltiles__data__)
	.dw	     _leveltiles__data__
	.dw	LL0+0

	.bss
_knight_x:		.ds	2
_knight_y:		.ds	2
_tics_knight:		.ds	2
_frame_knight:		.ds	2
_state_knight:		.ds	2
_dir_knight:		.ds	2
_walk_knight:		.ds	2
_j1:		.ds	2
_ennemy_x:		.ds	2
_ennemy_y:		.ds	2
_univers_time:		.ds	2
_time_move:		.ds	2
_counter:		.ds	2
_table_x:		.ds	32
_table_y:		.ds	32
_table_z:		.ds	32
_nb_ennemy:		.ds	2
_table_x_2:		.ds	32
_table_y_2:		.ds	32
_table_z_2:		.ds	32
_nb_ennemy_2:		.ds	2
_table_x_3:		.ds	32
_table_y_3:		.ds	32
_table_z_3:		.ds	32
_nb_ennemy_3:		.ds	2
_ram_knight_addr:		.ds	2
_ram_knight_addr2:		.ds	2
__arg:

;0 error(s) in compilation
;	literal pool:42
;	constant pool:10
;	global pool:2464
;	Macro pool:1204
